-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 19:24:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mini_mercado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mini_mercado` ;

-- -----------------------------------------------------
-- Schema mini_mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_mercado` DEFAULT CHARACTER SET utf8 ;
USE `mini_mercado` ;

-- -----------------------------------------------------
-- Table `mini_mercado`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Empleados` (
  `id_Empleados` INT(20) NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `num_identificacion` VARCHAR(11) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_Empleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Usuarios` (
  `id_Usuarios` INT(20) NOT NULL,
  ` nombre` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `Empleados_id_Empleados` INT(20) NOT NULL,
  PRIMARY KEY (`id_Usuarios`),
  CONSTRAINT `fk_Usuarios_Empleados1`
    FOREIGN KEY (`Empleados_id_Empleados`)
    REFERENCES `mini_mercado`.`Empleados` (`id_Empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuarios_Empleados1_idx` ON `mini_mercado`.`Usuarios` (`Empleados_id_Empleados` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Proveedores` (
  `id_Proveedores` INT(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_Proveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Productos` (
  `id_Productos` INT(20) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  `Proveedores_idProveedores` INT NOT NULL,
  PRIMARY KEY (`id_Productos`),
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `mini_mercado`.`Proveedores` (`id_Proveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_Proveedores1_idx` ON `mini_mercado`.`Productos` (`Proveedores_idProveedores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Inventario` (
  `id_Inventario` INT(20) NOT NULL,
  `stock` VARCHAR(20) NOT NULL,
  `fecha` VARCHAR(11) NOT NULL,
  `Productos_idProductos` INT(20) NOT NULL,
  `Proveedores_idProveedores` INT NOT NULL,
  PRIMARY KEY (`id_Inventario`),
  CONSTRAINT `fk_Inventario_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mini_mercado`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `mini_mercado`.`Proveedores` (`id_Proveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inventario_Productos1_idx` ON `mini_mercado`.`Inventario` (`Productos_idProductos` ASC) VISIBLE;

CREATE INDEX `fk_Inventario_Proveedores1_idx` ON `mini_mercado`.`Inventario` (`Proveedores_idProveedores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Clientes` (
  `id_Cliente` INT(20) NOT NULL,
  `nombre` VARCHAR(10) NOT NULL,
  `apellido` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Facturas` (
  `id_Facturas` INT(20) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `fecha` VARCHAR(20) NOT NULL,
  `valor_uni` DECIMAL(6,2) NOT NULL,
  `valor_total` DECIMAL(6,2) NOT NULL,
  `valor_pagar` DECIMAL(6,2) NOT NULL,
  `Usuarios_id_Usuarios` INT(20) NOT NULL,
  `Productos_id_Productos` INT(20) NOT NULL,
  `Clientes_idCliente` INT(20) NOT NULL,
  PRIMARY KEY (`id_Facturas`),
  CONSTRAINT `fk_Facturas_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mini_mercado`.`Clientes` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `mini_mercado`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Usuarios1`
    FOREIGN KEY (`Usuarios_id_Usuarios`)
    REFERENCES `mini_mercado`.`Usuarios` (`id_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Facturas_Clientes1_idx` ON `mini_mercado`.`Facturas` (`Clientes_idCliente` ASC) VISIBLE;

CREATE INDEX `fk_Facturas_Productos1_idx` ON `mini_mercado`.`Facturas` (`Productos_id_Productos` ASC) VISIBLE;

CREATE INDEX `fk_Facturas_Usuarios1_idx` ON `mini_mercado`.`Facturas` (`Usuarios_id_Usuarios` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
