-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 19:24:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mini_mercado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mini_mercado` ;

-- -----------------------------------------------------
-- Schema mini_mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_mercado` DEFAULT CHARACTER SET utf8 ;
USE `mini_mercado` ;

-- -----------------------------------------------------
-- Table `mini_mercado`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Empleados` (
  `id` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `num_identificacion` VARCHAR(11) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mini_mercado`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  `rol_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_Usuarios_Rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `mini_mercado`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuarios_Rol_idx` ON `mini_mercado`.`Usuarios` (`rol_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  `proveedores_id` INT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `mini_mercado`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_Proveedores1_idx` ON `mini_mercado`.`Productos` (`proveedores_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Inventario` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `productos_id` INT(20) NOT NULL,
  `proveedores_id` INT NOT NULL,
  `stock` VARCHAR(500) NOT NULL,
  `fecha` DATE NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_Inventario_Productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mini_mercado`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `mini_mercado`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inventario_Productos1_idx` ON `mini_mercado`.`Inventario` (`productos_id` ASC) VISIBLE;

CREATE INDEX `fk_Inventario_Proveedores1_idx` ON `mini_mercado`.`Inventario` (`proveedores_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Clientes` (
  `id` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(200) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_mercado`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_mercado`.`Facturas` (
  `id` INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `usuarios_id` INT(20) NOT NULL,
  `productos_id` INT(20) NOT NULL,
  `clientes_id` INT(20) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `fecha` VARCHAR(20) NOT NULL,
  `valor_uni` DECIMAL(6,2) NOT NULL,
  `valor_total` DECIMAL(6,2) NOT NULL,
  `valor_pagar` DECIMAL(6,2),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_Facturas_Clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `mini_mercado`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mini_mercado`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_Usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mini_mercado`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Facturas_Clientes1_idx` ON `mini_mercado`.`Facturas` (`usuarios_id` ASC) VISIBLE;

CREATE INDEX `fk_Facturas_Productos1_idx` ON `mini_mercado`.`Facturas` (`productos_id` ASC) VISIBLE;

CREATE INDEX `fk_Facturas_Usuarios1_idx` ON `mini_mercado`.`Facturas` (`usuarios_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
